name: Build Distribution Files

on:
  push:
    branches:
      - main
  pull_request:
  release:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Create dist Folder
      run: "mkdir -p dist"
    - name: Remove existing dist files
      run: "rm -f dist/*"
    - name: Copy files to dist folder
      run: "cp *.{js,py,json} dist/"
    - name: Minify JavaScript
      uses: nizarmah/auto-minify@v2.1
      with:
        directory: 'dist'
        js_engine: 'uglify-js'
    - name: Commit Distribution Files
      uses: stefanzweifel/git-auto-commit-action@v4
      if: ${{ github.event_name == 'release' }}
      with:
        repository: 'dist'
        commit_message: "Github Action: JS Distribution files"
        branch: ${{ github.ref }}